language: ruby
rvm:
- 2.4

install:
 - gem install jekyll bundler

before_script:
 - bundle install

script: bundle exec jekyll build && bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
