language: ruby
cache:
  bundler: true
  directories:
   - /home/travis/.rvm/

rvm:
- 2.4

script: bundle exec jekyll build

after_script: bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
