language: ruby
cache:
  bundler: true
  directories:
   - /home/travis/.rvm/

rvm:
- 2.4

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --url-ignore "//github.com/ApptuitAI/documentation/edit/master/_docs/" ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
