# Site settings
title: ApptuitAI Documentation
email: hello@apptuit.ai
description: >- # this means to ignore newlines until "baseurl:"
  Documentation site for apptuit.ai - cloud scale monitoring and analytics,
  radically re-imagined with Artificial Intelligence. Try it for free.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics_key:
show_full_navigation: true

# jekyll-seo-tag settings
# see https://github.com/jekyll/jekyll-seo-tag
#logo: /siteicon.png
#description: ApptuitAI Documentation
#author:
#  name:
#  email:
#  twitter: # twitter username without the @ symbol
#social:
#  name: ApptuitAI Documentation
#  links:
#    - https://docs.apptuit.ai



# Build settings
markdown: kramdown

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-font-awesome-sass

font-awesome:
  assets: true

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: docs
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENCE
